### ISSUE TITLE
TemplatesFinder has the same issue as the Partials Finder used to have.

### ISSUE THREAD

**Issue by nessur** [hanami/view#100]
Nearly identical to the issue fixed here: https://github.com/hanami/view/pull/73

This code is ambiguous: 
`Hanami::View::Rendering::TemplatesFinder.new(Articles::Show).find`
When these files exist:
`apps/web/templates/members/articles/show.html.erb`
`apps/web/templates/articles/show.html.erb`

B/c the `def _find` method just calls:
`Dir.glob( "#{ [root, lookup, template_name].join(separator) }.#{ format }.#{ engines }" )`

My classes look like this:
```
module Web::Views::Articles
  class Index
    include Web::View
    template 'articles/index'
  end
end
```
and
```
module Web::Views::Members::Articles
  class Index
    include Web::View
    template 'members/articles/index'
  end
end
```

This is the Great Understanding I came to when I saw my app work successfully locally, but fail when deployed, I suppose the directories were created in a different order, such that the wrong one was always returned first on the remote server.

**Comment by jodosha** [comment]
Fixed by #101
