### ISSUE TITLE
Hanami::Presenter turns private methods into public ones

### ISSUE THREAD

**Issue by mereghost** [hanami/view#102]
Consider the following example:

```ruby
class AwesomePresenter
  include Hanami::Presenter

  private

  def a_method
    puts "You should not pry in the private lives of others"
  end
end

contrived_example = AwesomePresenter.new(Object.new)
contrived_example.public_methods.include? :a_method      #=> true
contrived_example.a_method    #=> "You should not pry in the private lives of others"
```

What I expected is that it would return false and not being able to be called with a receiver other than `self` as `SimpleDelegator` does.

Also, is there a reason that it does not use `SimpleDelegator` or tries to implement `Delegator` at all?

**Comment by mereghost** [comment]
Dumb me forgot that `Hanami::Presenter` is a module, so forget about the `SimpleDelegator` stuff. :dizzy_face:

**Comment by mereghost** [comment]
Investigating a bit it seems that the problem lies in [`Hanami::View::Escape.method_added`](https://github.com/hanami/view/blob/master/lib/hanami/view/escape.rb#L167).

Since the callback does not know anything about method visibility (just the methods name), it just redefines it as public.

And it also explains why I was getting escaped content out of a presenter in a view, which quite baffled me at first.

**Comment by mereghost** [comment]
The simplest fix I found was just to make a check if the method is public. If not, then the class attribute `autoescape_methods` should be set to false, which will skip the whole thing thanks to that `unless` clause.

```ruby
autoescape_methods[method_name] = !public_methods.include?(method_name)
```

I haven't found another place that's using `autoescape_methods` in the project, so a better implementation (IMHO) would be:

```ruby
def self.extended(base)
  base.class_eval do
    include ::Hanami::Utils::ClassAttribute
    include ::Hanami::View::Escape::InstanceMethods

    class_attribute :autoescape_methods
    self.autoescape_methods = Hash.new(false) 
  end
end

def method_added(method_name)
  autoescape_methods[method_name] = public_methods.include?(method_name)
  if autoescape_methods[method_name]
    prepend Module.new {
      module_eval %{
        def #{ method_name }(*args, &blk); ::Hanami::View::Escape.html super; end
       }
    }
    autoescape_methods[method_name] = false
end
```

That way we stay positive (as Avid Grimm would say) and avoid so many negatives on the code.

I can send a PR with the changes, just tell me the branch which I should send it too. =)

**Comment by jodosha** [comment]
@mereghost Magic code always bites..

I'm sorry about this issue. I guess one possible way to fix this is to check the visibility by using `public_instance_methods`, `protected_instance_methods` and `private_instance_methods`, and set same visibility.

Does it makes sense?

**Comment by mereghost** [comment]
@jodosha Heh, no worries. I tend to look at every nook an cranny of the software I use, so I only can thank you for keeping up with the issues I'm opening. =)

That would make sense, but IMO only the public interface should be autoescaped as it's the only that should ever be used unless for some reason they can be called inside the templates (which I think is not the case nor desirable).

I did some tests on this and skipping the protected + private methods breaks some of the tests but I have not checked why yet.

**Comment by mereghost** [comment]
After some digging around I found out that I was just being dumb. I was calling `public_methods` and not `public_instance_methods` as a guard clause on the `method_added` method and that breaks everything.

**Comment by jodosha** [comment]
@mereghost Does `public_instance_methods` solves the problem?

**Comment by mereghost** [comment]
Yep. I ran implementation with the following line added:
```ruby
return unless public_instance_methods.include? method_name
# ... same implementation as before
```

If you think it's better, tho, it's possible to check in which access level each method is and just append that before the method declaration on the prepended module. While I would find weird that my strings are being escaped outside the exposed interface, it would make treat all strings in the same way so less surprising (if documented).

**Comment by jodosha** [comment]
@mereghost https://github.com/hanami/view#presenter-autoescape Do you think is this enough?
I've just checked on Guides and we miss an article about presenters.

In the meantime, would you like to write a fix for this problem? Thank you very much! 👍

**Comment by mereghost** [comment]
Sure. I'll send a PR later this week. =)
