### ISSUE TITLE
local with unknown key prints to html

### ISSUE THREAD

**Issue by TiteiKo** [hanami/view#106]
I don't know how to formulate the title better... 

To be really simple: 

```haml
!!!
%html
  %head
    %title Web
    = favicon
  %body
    = local(:foo)
```

generates

```html
<!DOCTYPE html>
<html>
  <head>
    <title>Web</title>
    <link href="/assets/web/favicon.ico" rel="shortcut icon" type="image/x-icon">
  </head>
  <body>
    #<Hanami::View::Rendering::NullLocal:0x007f82e3bd73e8>
  </body>
</html>
```

Using ```local(:foo).to_s``` gives the same

Only by using ```local(:foo).to_str``` gives the expected result:

```html
<!DOCTYPE html>
<html>
  <head>
    <title>Web</title>
    <link href="/assets/web/favicon.ico" rel="shortcut icon" type="image/x-icon">
  </head>
  <body>
    
  </body>
</html>
```

Adding the following ```#to_s``` method to Hanami::View::Rendering::NullLocal is enough to obtain the logically expected output. Unless there's a reason not to? 

```ruby
def to_s
  to_str   # or TO_STR
end
```

For versions references: http://0bin.net/paste/2RiASve4iefyZ+Co#UrbYcXYSbimlQwyRqba1vviD93uD+ql7KWx30cJ6mrE

**Comment by cllns** [comment]
Instead of `local(:foo)` does just `foo` work, or `locals[:foo]` ?

**Comment by TiteiKo** [comment]
foo => throws an error when the action/view does not have the method

locals[:foo] => never renders anything, locals being an empty hash

**Comment by cllns** [comment]
Thanks. Can you post what your View looks like?

**Comment by duykhoa** [comment]
It looks like `foo` isn't defined in your view

Here is the source of `local`

```
          def local(key)
            if respond_to?(key)
               __send__(key)
            else
              locals.fetch(key) { NullLocal.new(key) }
            end
        end
```

So if your view has the `foo` method, it'll call first. If not, it will check in the `locals` hash.
And if they key isn't exist in the `locals` hash, it returns a NullLocal object as your code above.

Just guess, rofl

**Comment by TiteiKo** [comment]
@clins https://github.com/TiteiKo/hanami-null-local-issue

* ```/foo``` should display ```foo```
* ```/bar``` should display nothing but displays ```#``` (```#<Hanami::View::Rendering::NullLocal:0x007f82e3bd73e8>``` in the source, being interpreted as a html tag by chrome)

------

I did a few more tests this morning, this behaviour happens with haml, but not with erb or slim. 

My guess is that for erb and slim, having the object ```.nil? => true``` is enough for them to just skip it, instead of haml which calls ```.to_s``` on it.


Anyway, the following is not something one would expect in Ruby:

```ruby
irb(main):001:0> Hanami::View::Rendering::NullLocal.new(:foo).to_str
=> ""
irb(main):002:0> Hanami::View::Rendering::NullLocal.new(:foo).to_s
=> #<Hanami::View::Rendering::NullLocal:7fc8d5ad1a88 :foo.to_s>
```

**Comment by jodosha** [comment]
@TiteiKo Thanks for reporting this. Yes, it was only tested with ERb on my side, so `#to_str` was enough. You're right, we should add an alias `#to_s` to make it to work. 👍
