### ISSUE TITLE
Migrate from Minitest to RSpec

### ISSUE THREAD

**Issue by jodosha** [hanami/view#120]
A few rules to follow:

  * If you want to work on this, please leave a comment here. We want to avoid many people to work on the same task.

  * We expect this migration to happen within a week from now.

  * Do not change the tests, only migrate from Minitest to RSpec syntax. If not sure, please ask here.

  * Do not remove the old tests, only add the new ones.

  * Make CI build to use RSpec tests.

  * **Target `develop` branch, instead of `master`.**

  * All the tests artefacts like fixtures, goes under `spec/support`.

  * Try to reflect the structure under `lib/`. Eg. `lib/hanami/view.rb` should be tested under `spec/hanami/view_spec.rb`, while `test/rendering_test.rb` should go under `spec/integration/rendering_spec.rb`.

If you want to take inspiration, please have a look at: https://github.com/hanami/mailer/pull/67

**Comment by jodosha** [comment]
@nerdinand is in charge for this.

**Comment by sahithi-ihtihas** [comment]
@jodosha   I am beginner and would like to take up the issue. Can you please guide me in doing that ?

**Comment by jodosha** [comment]
@sahithi-ihtihas I'm sorry but @nerdinand is already working on this. Please see #121.

Would you like to take another framework? See http://bit.ly/hanami-help-wanted

**Comment by jodosha** [comment]
Implemented by #121
