### ISSUE TITLE
form_for helper in slim template

### ISSUE THREAD

**Issue by sakuro** [hanami/view#122]
From [discourse topic](https://discourse.hanamirb.org/t/form-for-helper-in-slim-template/327):

I am [replacing ERb templates with Slim in the Bookshelf app](https://github.com/sakuro/bookshelf) of the Getting Started guide.
But I found it is difficult to translate the use of Hanami's `form_for` helper in ERb templates to Slim since Slim is line oriented and [multiple lines must be joined with backslashes](http://www.rubydoc.info/gems/slim/file/README.md#Output__).

Compare the two.

ERb:
```erb
<%=
  form_for :book, routes.books_path do
    div class: 'input' do
      label      :title
      text_field :title
    end

    div class: 'input' do
      label      :author
      text_field :author
    end

    div class: 'controls' do
      submit 'Create Book'
    end
  end
%>
```

Slim:
```slim
= form_for :book,  routes.books_path do \
  div class: 'input' do \
    label :title; \
    text_field :title \
  end; \
  div class: 'input' do \
    label :author; \
    text_field :author \
  end; \
  div class: 'controls' do \
    submit 'Create Book' \
  end
```

It could be nice if we can write forms in Slim less cumbersome way.

@jodosha advices that capturing would help.  Slim's capturing feature is described in [Helpers, capturing and includes](http://www.rubydoc.info/gems/slim/file/README.md#Helpers__capturing_and_includes) section of its README.

thoughts?

**Comment by TrevorBramble** [comment]
This is one of the things I mentioned on our call awhile back @jodosha. =^)

**Comment by jodosha** [comment]
Because we have native support for ERB, HAML, and Slim, it's worth to have adapters for these three template engines in order to support "capturing".

We could transform:

```erb
<%=
  form_for :book, routes.books_path do
    div class: 'input' do
      label      :title
      text_field :title
    end

    div class: 'controls' do
      submit 'Create Book'
    end
  end
%>
```

Into the more familiar form for Ruby developers:

```erb
<%= form_for :book, routes.books_path do |f| %>
  <div class="input">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="controls">
    <%= f.submit "Create Book" %>
  </div>
<% end %>
```

---

This is a breaking change that should target 2.0. What @hanami/core think?

**Comment by cllns** [comment]
Don't we want to encourage `form_for` to go into the view, rather than the template? 

I like the the current syntax but I'm okay with switching if there's a strong need for it :)

**Comment by TiteiKo** [comment]
In slim you can write your forms like this:

```ruby
= form_for :book, routes.books_path do
  - div class: 'input'
    - label :title
    - text_field :title

  - div class: 'controls'
    - submit 'Create Book'
```

**Comment by TiteiKo** [comment]
@cllns I'm don't think the all form should go in the view. There's way too many templating informations in it (divs, labels, grid stuff....)

Instead what I like to do is this:

```ruby
# in the view
def creation_form
  Form.new(:book, routes.books_path, { book: book }, method: :post)
end

# in the template
= form_for creation_form, class: '' do
  - div class: 'input'
    - label :title
    - text_field :title

  - div class: 'controls'
    - submit 'Create Book'
```

**Comment by jodosha** [comment]
@cllns I always use them in the template. Having them in the view, is a workaround to DRY code between the "edit" and the "create" view/template. But this is another story.

I'd like to have that ERB/Slim syntax outlined in the comments above. The target should be 2.0.

@hanami/core WDYT?

**Comment by jodosha** [comment]
Closing this, as the discussion led to a solution for @sakuro. Thank you all!
