### ISSUE TITLE
Can't find a convenient way to display raw HTML content in hanami view

### ISSUE THREAD

**Issue by cuonggt** [hanami/view#123]
I have a sample content and expose it:

    module Web::Controllers::Welcome
      class Index
        include Web::Action

        expose :content

        def call(params)
          @content = '<h1>Hello World!</h1>'
        end
      end
    end

In view, I want to keep raw content:

    module Web::Views::Welcome
       class Index
         include Web::View

        def raw_content
          _raw content
        end
      end
    end

But when I display it in a template by using `<%= raw_content %>`, I still receive an escaped result, not a raw one.

How to display an unescaped data in Hanami templates?

@davydovanton @jodosha

**Comment by TiteiKo** [comment]
Hi @cuonggt, could you try with the following please?

```ruby
def raw_content
  raw content
end
```

**Comment by cuonggt** [comment]
@TiteiKo : thank you for reply. I tried but it still doesn't work. Did you ever try it?

**Comment by TiteiKo** [comment]
Hi @cuonggt 

So, turns out that [this line of code](https://github.com/hanami/view/blob/master/lib/hanami/view/rendering/scope.rb#L67) is the source of your problem.

Your `content` exposed by the action isn't itself escaped, its the view that escapes it when you call it. 

In a nutshell, this works:
```ruby
def raw_content
  raw CGI.unescapeHTML(content)
end
```

ping @jodosha @AlfonsoUceda @mereghost WDYT?

**Comment by davydovanton** [comment]
@cuonggt hey, I created the simple example for `raw` and `h` methods. You can find commit here:
https://github.com/hanami/contributors/commit/68b8bc1e79ac97bb6a74e49523969cebc25ef5fd

Ant this code returns this HTML data:
![screenshot 2017-04-21 12 48 13](https://cloud.githubusercontent.com/assets/1147484/25272649/5fc077e0-2691-11e7-981b-e770084c5400.jpeg)

I hope it will be helpful for you 👍

**Comment by jodosha** [comment]
@cuonggt Hi and sorry about this confusion. There is a guide article that describes [Markup Escape](http://hanamirb.org/guides/helpers/escape/) with a case similar to yours. It's probably worth to update it with your case too, as I think it's a common one.

---

This code works:

```ruby
module Web::Views::Home
  class Index
    include Web::View

    def content
      raw locals[:content]
    end
  end
end
```

```erb
<%= content %>
```

**Comment by cuonggt** [comment]
That is exactly thing that I need. Thank you @jodosha.
