### ISSUE TITLE
Sublayouts like Rails

### ISSUE THREAD

**Issue by yjukaku** [hanami/view#125]
In Rails, we can use 'sublayouts' which are layout files that are rendered within another layout:

```erb
# parent.html.erb
<h1>Hi</h1>
<div class='content'>
  <% if content_for?(:sub_content) %>
    <% yield :sub_content %>
  <% else %>
    <%= yield %>
  <% end %>
</div>
```
```html
# child_layout.html.erb
<% content_for :sub_content do %>
  <div class='child'>
    Child content: <% yield %>
  </div>
<% end %>
<!-- render the parent layout, which then uses the sub_content defined above -->
<% render template: "layouts/parent" %>
```

Rendering something using the 'child_layout' layout would result in

```html
<h1>Hi</h1>
<div class='content'>
  <div class='child'>
     Child Content: <!-- content here -->
  </div>
</div>
```

Is this possible in Hanami?

**Comment by davydovanton** [comment]
Hey, I think you can use view objects for this. For example:
```ruby
module Web
  module Views
    class ApplicationLayout
      include Web::Layout

      def sub_content
        ''
      end
    end
  end
end

module Web::Views::Contributors
  class Index
    include Web::View

    def sub_content
      html.div(class: 'hello') { ... }
    end
  end
end

module Web::Views::Contributors
  class Index
    include Web::View
    # sub_content here is ''
  end
end

# => index page -> '<div class="hello"> ... </div>'
# => show page  -> ''
```

**Comment by yjukaku** [comment]
Yeah, I was afraid that a view was the only way. I was wondering if there was a way to implement the layout in an ERB file rather than using plain ruby code. 🤔

**Comment by yjukaku** [comment]
Actually, I don't think what you proposed works. How would I reuse the child template across multiple views? And how would I `yield` to the eg. index.html.erb content?

**Comment by davydovanton** [comment]
hey, sorry. I found other solution. I hope it will be more helpful for you :)
https://github.com/hanami/view#optional-content

**Comment by yjukaku** [comment]
Hmm, I did see those before but I'm not sure it's possible to do what I want. How would you use 'optional content' (`local`) to render one layout *inside* of another layout? It seems like `local` is for choosing what kind of content goes in specific areas of the page.

Thanks for your help.

**Comment by jodosha** [comment]
@yjukaku It looks like you found a solution for your question. Closing this. 😄

**Comment by yjukaku** [comment]
I actually don't think this has been answered, but I no longer am working on the project that needed this. What I had done was make a small patch to hanami view that would have allowed specifying the parent layout, because it didn't seem to be possible with what was available
