### ISSUE TITLE
Render specific partial from view object/action

### ISSUE THREAD

**Issue by davydovanton** [hanami/view#128]
Sometimes it's useful for render specific template in some cases. For example:
```ruby
module Web::Controllers::Repos
  class Index
    include Web::Action

    def call(params)
      if authenticated?
        render :index
      else
        render :promo_page
      end
    end
  end
end
```

I know that it looks like a code smell, but I think it will be a frequent question after rails or another web framework. WDYT should we decide how to resolve this issues or not? @hanami/core

**Comment by jodosha** [comment]
I really want to solve this problem, but I'm not sure yet which gem should include this feature (`controller`, `view`, or `hanami`). We should probably open a new forum thread instead.
