### ISSUE TITLE
Rendering a partial template from application layout breaks view rendering in unit test environment

### ISSUE THREAD

**Issue by michaellennox** [hanami/view#129]
**Description**

Adding a partial template to be rendered from the layout template using the `render partial: '<partial_name>'` method stops the `#render` method of the associated view working in a unit test environment.

**Repository with reproduction**

Master passes tests: https://github.com/michaellennox/partial_render_bug
Soon as partial is added to layout unit test breaks with backtrace below: https://github.com/michaellennox/partial_render_bug/tree/partial_breaks_rendering_in_tests
Diff between the two branches: https://github.com/michaellennox/partial_render_bug/compare/partial_breaks_rendering_in_tests

**Backtrace**

```
Web::Views::ApplicationLayout#test_0001_displays that things are there:
NoMethodError: undefined method `view' for #<Hanami::View::Template:0x007f817c440138>
    /Users/Michael/.rvm/gems/ruby-2.4.0/gems/hanami-view-1.0.0/lib/hanami/view/rendering/layout_scope.rb:108:in `view'
    /Users/Michael/.rvm/gems/ruby-2.4.0/gems/hanami-view-1.0.0/lib/hanami/view/rendering/layout_scope.rb:231:in `renderer'
    /Users/Michael/.rvm/gems/ruby-2.4.0/gems/hanami-view-1.0.0/lib/hanami/view/rendering/layout_scope.rb:90:in `render'
    /Users/Michael/Projects/bugs/partial_render_bug/apps/web/templates/application.html.erb:8:in `block in singleton class'
    /Users/Michael/Projects/bugs/partial_render_bug/apps/web/templates/application.html.erb:-6:in `instance_eval'
    /Users/Michael/Projects/bugs/partial_render_bug/apps/web/templates/application.html.erb:-6:in `singleton class'
    /Users/Michael/Projects/bugs/partial_render_bug/apps/web/templates/application.html.erb:-8:in `__tilt_70097016448220'
    /Users/Michael/.rvm/gems/ruby-2.4.0/gems/tilt-2.0.7/lib/tilt/template.rb:170:in `call'
    /Users/Michael/.rvm/gems/ruby-2.4.0/gems/tilt-2.0.7/lib/tilt/template.rb:170:in `evaluate'
    /Users/Michael/.rvm/gems/ruby-2.4.0/gems/tilt-2.0.7/lib/tilt/template.rb:109:in `render'
    /Users/Michael/.rvm/gems/ruby-2.4.0/gems/hanami-view-1.0.0/lib/hanami/view/template.rb:41:in `render'
    /Users/Michael/.rvm/gems/ruby-2.4.0/gems/hanami-view-1.0.0/lib/hanami/layout.rb:139:in `render'
    /Users/Michael/Projects/bugs/partial_render_bug/spec/web/views/application_layout_spec.rb:7:in `block (2 levels) in <top (required)>'
```

**Notes**

* Tested that issue occurs with both `.erb` and `.slim` templates
* Partial renders as expected in integration tests and manual tests

**The Test**

```ruby
# 'spec/web/views/application_layout_spec.rb'
require 'spec_helper'

describe Web::Views::ApplicationLayout do
  let(:exposures) { Hash[] }
  let(:template)  { Hanami::View::Template.new('apps/web/templates/application.html.erb') }
  let(:view)      { Web::Views::ApplicationLayout.new(template, exposures) }
  let(:rendered)  { view.render }

  it 'displays that things are there' do
    rendered.must_include '<p>Many Things are Here</p>'
  end
end
```

**The Template that passes tests**

```erb
# 'apps/web/templates/application.html.erb'
<!DOCTYPE html>
<html>
  <head>
    <title>Web</title>
    <%= favicon %>
  </head>
  <body>
    <p>Many Things are Here</p>
    <%= yield %>
  </body>
</html>
```

**The template that fails tests**

```erb
# 'apps/web/templates/application.html.erb'
<!DOCTYPE html>
<html>
  <head>
    <title>Web</title>
    <%= favicon %>
  </head>
  <body>
    <%= render partial: 'shared/misc_partial' %>
    <p>Many Things are Here</p>
    <%= yield %>
  </body>
</html>
```

**The associated partial template**

```erb
# 'apps/web/templates/shared/_misc_partial.html.erb'
<p>I somehow break things</p>
```

**The layout view**

```ruby
# 'apps/web/views/application_layout.rb'
module Web
  module Views
    class ApplicationLayout
      include Web::Layout
    end
  end
end
```

@cllns

**Comment by jodosha** [comment]
@michaellennox Hi, I'm sorry but it isn't possible to unit test layouts right now. The setup for a layout is quite complex and its `#initialize` signature is different from a view: https://github.com/hanami/view/blob/master/lib/hanami/layout.rb#L122-L126.

It's marked as `private` API for this purpose. You can indirectly test it, by rendering a view and asserting if the markup is the expected one.

**Comment by caiges** [comment]
Maybe the generator should remove the default application layout spec until the testing layouts becomes more feasible? I ran into this yesterday from a newly generated app (using haml and minitest).

**Comment by javimbk** [comment]
Got the same problem as @caiges , it was really confusing for me and even though I searched in Google couldn't find anything. I'm saying +1 on his suggestion since it can lead you to think that you have done something wrong.
