### ISSUE TITLE
Custom error page not rendered on view and template errors

### ISSUE THREAD

**Issue by cveneziani** [hanami/view#138]
I've implemented a custom error page for the 500 code status. I've followed this guide: http://hanamirb.org/guides/1.0/views/custom-error-pages/

It turns out that in production my custom page is displayed only on errors that occur within the controller. But when an error occurs either in the view or in the template, the custom page is not used. Instead I get the "**Internal server error**" page provided by the server.

On top of that, the bug tracker is not fired.

What can I do to fix that?

**Comment by AlfonsoUceda** [comment]
@cveneziani thanks for letting us know, I'll check as soon as posible.

**Comment by AlfonsoUceda** [comment]
@cveneziani I can confirm that this is a bug, I'll try to fix as soon as possible. Thanks!

**Comment by cveneziani** [comment]
Thanks :)

**Comment by AlfonsoUceda** [comment]
This is not a bug in hanami/view, it's a bug in hanami gem, I'll open an issue in hanami repo linking it here.

**Comment by AlfonsoUceda** [comment]
Superseed by https://github.com/hanami/hanami/issues/865
