### ISSUE TITLE
Partial templates that can yield

### ISSUE THREAD

**Issue by malin-as** [hanami/view#141]
Hi,

I've had this requirement from time to time, I don't know if there is a specific name for it. I have a big chunk of HTML that I use on different pages, but I want to be able to customise something inside it. So I'm going to use small examples that aren't worth the trouble, but in practice it can be large templates, and the nesting makes sense. I'm using Slim:

```ruby
div.container
  = render partial: './my_partial' do
    | This is the content for my page #1
```

And the partial goes like this:
```ruby
nav
  a.nav-item
  a.nav-item
div.decoration
  = yield
```

This is currently not working.

I hacked into the code, changed two lines and now it works, cf 7ad6120ba9b26f50d6d36dc5ebff990e9e794700 . But I have no idea why it was not possible in the first place, so maybe it's not supposed to work this way. And I also don't know how to write a spec for that use case, so I'd like further input before doing any kind of pull request.

**Comment by AlfonsoUceda** [comment]
Hi @malin-as, can you tell us the folder's structure of the partials? one more thing, can you test against branch `139-local-overwrite`?

**Comment by malin-as** [comment]
Hi @AlfonsoUceda, I use the following files:
```
apps/web/templates/story/new.html.slim
apps/web/templates/_my_partial.html.slim
```
I had some trouble in the past with partials stored elsewhere than directly in the `templates` directory, and never took the time to investigate, so for now I stick to this format.

I patched the `139-local-overwrite` with my commit, and still get the expected result. All the tests (for hanami-view) succeed.

**Comment by AlfonsoUceda** [comment]
@malin-as can you follow this guide? http://hanamirb.org/guides/1.1/views/layouts/#optional-content

So you can get rid of that hack, I think what you are trying to achieve can be reached with that guide.

**Comment by malin-as** [comment]
@AlfonsoUceda yes, I think it is possible but it makes for a very messy piece of code. What I'm precisely trying to do is to have a markdown editor (a simple one, at the moment) that I can use in different pages of my app. Right now, the partial template looks like that:

```slim
div
  nav.nav.nav-tabs role='tablist'
    a.nav-item.nav-link.active href='#md-tab-edit' role='tab' data-toggle='tab'
      = I18n.t('global.form.md.edit.edit')
    a#md-nav-preview.nav-item.nav-link href='#md-tab-preview' role='tab' data-toggle='tab'
      = I18n.t('global.form.md.preview')
      = image('spinner.svg', id: 'md-nav-preview-spinner', class: 'd-none')

  div.tab-content
    div#md-tab-edit.tab-pane.show.active role='tabpanel'
      div#md-edit-toolbar.btn-toolbar role='toolbar'
        div.btn-group.mr-2 role='group'
          button#md-button-bold.btn.btn-outline-secondary.btn-sm type="button" data-toggle='tooltip' data-placement='top' title=I18n.t('global.form.md.edit.bold')
            b b
          button#md-button-italic.btn.btn-outline-secondary.btn-sm type="button" data-toggle='tooltip' data-placement='top' title=I18n.t('global.form.md.edit.italic')
            i i
          button#md-button-underline.btn.btn-outline-secondary.btn-sm type="button" data-toggle='tooltip' data-placement='top' title=I18n.t('global.form.md.edit.underlined')
            u u
        div.btn-group.mr-2 role='group'
          button#md-button-inline-code.btn.btn-outline-secondary.btn-sm type="button" data-toggle='tooltip' data-placement='top' title=I18n.t('global.form.md.edit.inline-code')
            | $
          button#md-button-multiline-code.btn.btn-outline-secondary.btn-sm type="button" data-toggle='tooltip' data-placement='top' title=I18n.t('global.form.md.edit.multiline-code')
            | C
      div#md-edit-area
        = yield

    div#md-tab-preview.tab-pane.border.border-top-0 role='tabpanel'
      div#md-preview-area data-csrf-token=session[:_csrf_token] data-url=routes.previewmd_path
```

I yield the creation of the textarea so that it can be done by the calling template in whichever way it wants. Right now the textarea creation is done without the form helpers because they don't seem to interact well with Slim (maybe I could open a separate bug report about that).

If I have to generate that with the html helpers:

- I'm losing all the advantages of Slim (brevity and clarity of code)
- the code in the included modules of a view or a controller is not reloaded (I guess a problem with shotgun?) so I need to restart my server at every single change

**Comment by AlfonsoUceda** [comment]
@malin-as two points:
> . Right now the textarea creation is done without the form helpers because they don't seem to interact well with Slim

I think we need to fix this, can you open an issue with the problem?

> the code in the included modules of a view or a controller is not reloaded (I guess a problem with shotgun?) so I need to restart my server at every single change

Please, remove shotgun from your Gemfile and this gem `hanami-reloader`, right now is in experimental phase but I've talked with @jodosha and it works well, can you try that?.

IMO, we shouldn't support yield blocks when rendering partials but I don't know what other people think.

**Comment by gizotti** [comment]
@AlfonsoUceda my two cents in this matter.

IMO supporting yield blocks when rendering partials can bring benefits if trying to implement a different frontend architecture than the default one used by hanami.

An example of that is building components using partials (https://evilmartians.com/chronicles/evil-front-part-1 for more info) that I am trying to replicate in Hanami.

#143 has a better explanation of what I am trying to do. 😄

**Comment by jodosha** [comment]
@malin-as The feature looks interesting. Would you please open a PR with your feature? Please remember to use `develop` branch as base.

**Comment by jodosha** [comment]
Implemented by https://github.com/hanami/view/pull/163
