### ISSUE TITLE
Ignore `.orig` files in template folders

### ISSUE THREAD

**Issue by cllns** [hanami/view#148]
I just resolved a git merge and it left a `apps/web/templates/application.html.slim.orig` file lying around. When I go to any path, I get the following error:

```
RuntimeError: No template engine registered for application.html.slim.orig

/Users/sean/.gem/ruby/2.5.1/gems/hanami-1.2.0/lib/hanami/components/components.rb:474:in `module_eval'
/Users/sean/.gem/ruby/2.5.1/gems/tilt-2.0.8/lib/tilt.rb:43:in `new'
/Users/sean/.gem/ruby/2.5.1/gems/hanami-view-1.2.0/lib/hanami/view/template.rb:12:in `initialize'
/Users/sean/.gem/ruby/2.5.1/gems/hanami-view-1.2.0/lib/hanami/view/rendering/templates_finder.rb:73:in `new'
```
It's easy enough to fix: just delete that file. But it's a pain, and kind of surprising.

I think we should ignore `.orig` files, since they're definitely not supposed to be template files. We shouldn't try to load them into `tilt`.

**Comment by cllns** [comment]
@jodosha It's an artifact of `git mergetool`, it saves the unresolved file as a backup, incase you messed up the merge. It looks like it can [be disabled](https://stackoverflow.com/a/1627557) but that's not the default setting.

**Comment by jodosha** [comment]
@cllns I'm against this change then. Because if we go down the rabbit hole of ignoring all the artifacts generated by developer tools (git, IDE, text editors), we'll have a long blacklist of file extension to maintain. 👎

**Comment by cllns** [comment]
I don't think we have to go down the rabbit hole of ignoring all the artifacts generated by developer tools. In this case, every user will be using source control. Almost every user will be using git, and the ones that don't will likely be using mercurial, which also generates these `.orig` files.

**Comment by cllns** [comment]
Ok! I'm not sure what your workflow for merging branches is, but it's clearly different from mine (or you have `mergetool.keepBackup false` in your gitconfig :)

**Comment by jodosha** [comment]
@cllns This is my configuration https://github.com/jodosha/dotfiles/blob/master/.gitconfig

Which tool do you use to merge?
