### ISSUE TITLE
spec randomly fails: Hanami::View::MissingTemplateError

### ISSUE THREAD

**Issue by MITSUBOSHI** [hanami/view#168]
## Problems
- https://github.com/hanami/view/blob/9af8499ae1e7ce81c7eb85167222d9b3bfff2ec7/spec/unit/hanami/view/rendering/layout_scope_spec.rb#L113-L120
  - this example fails randomly.

### Causes
-  https://github.com/hanami/view/blob/9af8499ae1e7ce81c7eb85167222d9b3bfff2ec7/spec/support/rspec.rb#L23
    - `hanami-view` executes spec randomly.
- https://github.com/hanami/view/blob/9af8499ae1e7ce81c7eb85167222d9b3bfff2ec7/spec/unit/hanami/view_spec.rb#L344-L346
    - this spec does `Hanami::View.unload! ` when before hooks. So, it changes `Hanami::View`'s settings globally(even for the other specs).
- https://github.com/hanami/view/blob/9af8499ae1e7ce81c7eb85167222d9b3bfff2ec7/lib/hanami/view/rendering/template.rb#L44
  - Then, `template` method just returns `nil`.

※details: [travis's sample](https://travis-ci.org/hanami/view/jobs/630998799?utm_medium=notification&utm_source=github_status)

## Steps to reproduce the problem
- `bundle exec rspec --order defined spec/unit/hanami/view_spec.rb spec/unit/hanami/view/rendering/layout_scope_spec.rb`
  - it fails when the order:  `spec/unit/hanami/view_spec.rb` ->  `spec/unit/hanami/view/rendering/layout_scope_spec.rb`
  - it passes when the order:  `spec/unit/hanami/view/rendering/layout_scope_spec.rb` -> `spec/unit/hanami/view_spec.rb`

**Comment by jodosha** [comment]
Fixed by https://github.com/hanami/view/pull/167
