### ISSUE TITLE
`content_for` block output in a layout includes the template output as well.

### ISSUE THREAD

**Issue by pat** [hanami/view#250]
Haven't yet figured out a fix, but: I'm finding that if I have a `content_for` _block_ setting content in a template, and being used in a layout, then the returned value includes the entire view, not just the block.

With this view:
```erb
<% content_for :stuff do %>
  <meta title="thing" />
<% end %>

<h1>Welcome</h1>
```

And this layout:
```erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Slice test</title>
    <%== content_for(:stuff) %>
  </head>
  <body>
    <%= yield %>
  </body>
</html>
```

I get this output:
```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Slice test</title>
        <meta title="thing" />

<h1>Welcome</h1>

  </head>
  <body>
      <meta title="thing" />

<h1>Welcome</h1>

  </body>
</html>
```

I first hit this with Slim, but have reproduced it in a test app with both Slim and ERB. Perhaps something to do with `yield` confusion? 🤷🏻‍♂️

I suspect `content_for` isn't documented, and so maybe isn't considered ready for us? (Also, the logic being used seems to exist in two places: `hanami` and `hanami-view` 🤔)

MRI 3.2.2, hanami* 2.1.0.rc2, macOS Sonoma. Not a production issue.

**Comment by timriley** [comment]
@pat Thanks for reporting this!

So I've just played around with implicit block capture across our support HTML template engines, and it seems they only do it for blocks within their "output tags" (such as `=` in Slim or `<%=` in ERB).

As such, when using `content_for` and passing a block, it looks like it will need to be done so via such a tag.

Fortunately, this is a straightforward change for us to support: we just need to make sure we return `nil` from `content_for` whenever it is being used to capture content. I've just done that in https://github.com/hanami/hanami/pull/1369.

Would you be able to give that branch a go and confirm that it works?

Thanks also for pointing out the duplication of content_for logic. The one we want to keep right now is in the Hanami gem; I'll remove the content_for code from this repo shortly.

**Comment by pat** [comment]
Thanks @timriley - just gave your branch a spin (and made sure to use the `=` in Slim / `<%=` in ERB), and it works as desired both where I first found the problem, and in the test app. Thanks for the quick fix! :)
